backend/.dockerignore, backend/.flaskenv, backend/.gitignore, backend/.pre-commit-config.yaml, backend/Dockerfile, backend/README.md, backend/api/api.py, backend/app.py, backend/db/access_database.py, backend/db/config_database.py, backend/db/models.py, backend/db/queries.py, backend/db/resources/database.ini, backend/docker-compose.yml, backend/pyproject.toml, backend/requirements.txt, backend/templates/base.html
Closes #7, tasks done:
contributor can also setup his/her IDE for save triggered check
Also:
- Edited `README.md` - added instructions for local setup and start
- Edited `.gitignore` and `.flaskenv`- small adjustments
- Added `.dockerignore` file - so there are no unnecessary files
- Added `.pre-commit-config.yaml` file - so contributor can easily install all necessary pre-commit hooks
- Added `pyproject.toml` - to exclude virtual enviroment files from black reformatting 
- Added `templates/base.html` file - just to test database
=> Backend setup

backend/api/api.py, backend/db/models.py, backend/db/queries.py, backend/static/swagger.json, backend/templates/base.html
Update databazy podla modelu 7.11.2021
=> Update databazy 

frontend/tablet/App.tsx
- Cleaned app screen from NewAppScreen stuff 
- Replaced with Hello World, just for placeholder
=> Cleaned app screen (tablet_app)

frontend/tablet/App.tsx, frontend/tablet/package.json, frontend/tablet/src/screens/MainScreen.tsx, frontend/tablet/src/screens/index.ts, frontend/tablet/src/screens/room.tsx, frontend/tablet/yarn.lock
- Add required dependencies for navigation
- Add **index.ts** and **MainScreen.tsx** in _src/screens_ with no layout setup
- Setup navigation for room screen in **App.tsx**
=> Room screen navigation (tablet_app)

frontend/admin/src/authProvider.tsx, frontend/admin/src/components/Tenant/TenantShow.tsx
=> Admin fixes

frontend/tablet/app.json, frontend/tablet/ios/Podfile.lock, frontend/tablet/ios/tablet.xcodeproj/project.pbxproj, frontend/tablet/ios/tablet.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Update settings for iOS - iPad display full screen.
=> feat(iOS): update settings to display fullscreen

frontend/tablet/App.tsx, frontend/tablet/package.json, frontend/tablet/react-native.config.js, frontend/tablet/src/screens/MainScreen.tsx, frontend/tablet/src/screens/index.ts, frontend/tablet/yarn.lock
- Update react-native dependency to 0.66.3 in _frontend/tablet/package.json_ and _frontend/tablet/yarn.lock_,
- Fixed code format in all _frontend/tablet_ files.
=> Fix code format (tablet_app)

frontend/admin/src/authProvider.tsx, frontend/admin/src/components/Tenant/TenantShow.tsx, frontend/admin/src/models.ts
- Added custom claims to work with login.
- Role and tenantId is now taken from firebase custom claims
- Changes in tenantShow are only cosmetic
=> Auth provider with firebase custom claims

frontend/admin/README.md
Edited readme instructions to start the admin panel app
=> Admin panel start instructions

frontend/tablet/App.tsx, frontend/tablet/src/components/Button.tsx, frontend/tablet/src/components/Screen.tsx, frontend/tablet/src/components/index.ts, frontend/tablet/src/components/theme.ts, frontend/tablet/src/screens/RoomDetailScreen.tsx, frontend/tablet/src/screens/index.ts, frontend/tablet/src/screens/index.tsx
Needs some work with the styles and margins. Extract the components from the screen and keep their individual style objects in their separate files.
=> [Tablet] Room detail basic layout

frontend/tablet/src/components/Button.tsx
Padding on the button used for height calculation was wrong - changed horizontal -> vertical.
=> Fix button height

frontend/tablet/android/app/src/main/java/com/tablet/MainApplication.java, frontend/tablet/android/settings.gradle, frontend/tablet/ios/Podfile, frontend/tablet/ios/Podfile.lock, frontend/tablet/package.json, frontend/tablet/react-native-radial-gradient.d.ts, frontend/tablet/src/components/Screen.tsx, frontend/tablet/yarn.lock
Try on android, please. I only tested on iOS.
=> Add gradient background

frontend/tablet/src/components/Button.tsx, frontend/tablet/src/components/Typography.tsx, frontend/tablet/src/components/index.ts, frontend/tablet/src/screens/RoomDetailScreen/Footer.tsx, frontend/tablet/src/screens/RoomDetailScreen/index.tsx
- Extract `footer` from `RoomDetailScreen `
- Add optional margin for `Button.tsx`
- Fix typo in `Typography` component props
=> [Tablet] Extract Footer from RoomDetailScreen

frontend/admin/src/models.ts, frontend/tablet/src/components/Screen.tsx, frontend/tablet/src/models.ts, frontend/tablet/src/screens/LoginScreen/index.tsx, frontend/tablet/src/screens/RoomDetailScreen/index.tsx, frontend/tablet/src/screens/RoomListScreen/index.tsx, frontend/tablet/src/screens/index.tsx
- Refactor the layout a bit to accommodate different types of screens
- Add navigation and basic screens
=> [Tablet] Add screens navigation

frontend/tablet/.gitignore, frontend/tablet/App.tsx, frontend/tablet/android/app/build.gradle, frontend/tablet/android/app/google-services.json, frontend/tablet/android/build.gradle, frontend/tablet/app.json, frontend/tablet/ios/GoogleService-Info.plist, frontend/tablet/ios/Podfile.lock, frontend/tablet/ios/tablet.xcodeproj/project.pbxproj, frontend/tablet/ios/tablet.xcworkspace/GoogleService-Info.plist, frontend/tablet/ios/tablet/AppDelegate.m, frontend/tablet/ios/tablet/Info.plist, frontend/tablet/package.json, frontend/tablet/src/authProvider.tsx, frontend/tablet/src/contexts/UserContext.tsx, frontend/tablet/src/screens/LoginScreen/index.tsx, frontend/tablet/src/screens/RoomListScreen/index.tsx, frontend/tablet/src/screens/index.tsx, frontend/tablet/yarn.lock
Closes #49 
- Add _Firebase_ login with email and password,
- Firebase setup for _Android_ and _iOS_,
- Tested only on _Android_, please test it on _iOS_.
I put `GoogleService-Info.plist` into `/ios/tablet.xcodeproj`, but I don´t know if this is right folder where to put this file, so please check it.
=> [Tablet] Firebase login with email and password

frontend/admin/package.json, frontend/admin/src/App.tsx, frontend/admin/src/components/LoginPage.tsx, frontend/admin/src/components/Room/RoomCreate.tsx, frontend/admin/src/components/Room/RoomEdit.tsx, frontend/admin/src/components/Room/RoomList.tsx, frontend/admin/src/components/Tenant/TenantList.tsx, frontend/admin/src/models.ts, frontend/admin/yarn.lock
1. Added google login to app
2. Small work with rooms:
- added autocomplete input
- restylized info display of rooms
=> [FE Admin] Google login and rooms

backend/app/__init__.py, backend/app/api/room.py, backend/app/daos.py, backend/app/static/swagger.json
Added: 
- api endpoints for room
- room endpoints to swagger
=> Backend admin api for rooms

frontend/admin/src/components/Room/RoomCreate.tsx, frontend/admin/src/components/Room/RoomList.tsx
Added functionality to room create component that does filter buildings based on city that has been selected by user
=> [FE Admin] Room create with building filter based on selected city

frontend/admin/package.json, frontend/admin/src/App.tsx, frontend/admin/src/components/LoginPage.tsx, frontend/admin/src/components/Menu.tsx, frontend/admin/src/components/User/UserList.tsx, frontend/admin/src/components/User/UserShow.tsx, frontend/admin/src/components/User/index.tsx, frontend/admin/yarn.lock
Closes #53 
Display screens based on tenantId and role.
Screen for unknown user (user that doesn't have tenantId or role) is displayed by component UserShow.
=> [FE Admin] Screens after login based on tenantId and role

backend/app/api/room.py, backend/app/daos.py, backend/app/static/swagger.json
- Refactored api methods to better suit https://github.com/marmelab/react-admin/tree/master/packages/ra-data-json-server
- Appended 's' to room endpoints 
- Updated room swagger according to changes in api
=> Refactored room api

backend/app/__init__.py, backend/app/api/calendar.py, backend/app/api/room.py, backend/app/daos.py, backend/app/static/swagger.json
Added calendar API
Changes in this PR:
- Created calendar.py in backend/app/api
-  Added GET [single, multiple], PUT, DELETE, POST calendar endpoints
- Added CalendarDAO to daos.py
- Updated swagger after adding calendar API
- Merged master branch to backend-api-calendar after solving conflicts
=> Added calendar API

backend/app/api/room.py, backend/app/daos.py
Changes in this PR:
- Fixed formatting in roomDAO
- Adjusted return values of roomDAO methods 
- get_one
- add_room
- update_room
- Changed responses, methods of room endpoints
- DELETE
- POST
=> Small changes to room api

backend/app/models.py
Added cascade method to ondelete parameter and passive_deletes in models.py
=> Added ondelete Cascade, passive_deletes to models

backend/app/models.py
Reverts vacuumlabs/cowork-reservation#64
=> Revert "Added ondelete Cascade, passive_deletes to models"

backend/app/__init__.py, backend/app/api/calendar.py, backend/app/api/event.py, backend/app/api/room.py, backend/app/daos.py, backend/app/static/swagger.json
Changes:
- Refactored daos 
- SharedDaoMethods class can now be inherited 
- Renamed few methods (Also changed calls to this methods in api/room.py and api/calendar.py)
- Created Event Api 
- Registered Event blueprint in app blueprints via __init__.py
- Created Event dao
- Updated swagger with changes
=> Added Event api and refactored dao

backend/app/__init__.py, backend/requirements.txt
=> Flask cors set up

backend/app/api/tenant.py, backend/app/daos.py, backend/app/firebase_utils.py, backend/app/static/swagger.json, backend/requirements.txt
Changes:
- updated ```requierments.txt``` with needed modules for firebase
- updated ```daos.py```
- updated ```swagger.json``` with tenant options
- created ```firebase_util.py``` to communicate with firebase
- updated ```tenant.py``` with new enpoints
=> Admin api tenants

backend/app/api/calendar.py, backend/app/api/room.py
Changed some endpoints (update, delete, create) in room and calendar api to allow only users with `TENANT_ADMIN` or `SUPER_ADMIN` claims.
=> Added endpoint protection with claims

frontend/admin/src/components/Room/RoomList.tsx, frontend/admin/src/components/Tenant/TenantCreate.tsx, frontend/admin/src/components/Tenant/TenantEdit.tsx, frontend/admin/src/components/Tenant/TenantList.tsx, frontend/admin/src/components/Tenant/TenantShow.tsx, frontend/admin/src/components/Tenant/index.tsx, frontend/admin/src/components/User/UserEdit.tsx, frontend/admin/src/components/User/UserList.tsx, frontend/admin/src/components/User/index.tsx
Added edit components for Tenant, User and Room
=> Edit components

frontend/admin/yarn.lock, frontend/shared/models.ts, frontend/shared/package.json, frontend/tablet/package.json, frontend/tablet/src/screens/RoomListScreen/RoomCard.tsx, frontend/tablet/src/screens/RoomListScreen/index.tsx, frontend/tablet/yarn.lock
Closes #79 
- Add `Event` type to shared package and edit `Room` type,
- Update shared package to version 1.0.2 in tablet and admin application,
- Add mock data in `RoomListScreen` for `City`, `Building` and `Event`,
- Display `City` name and `Building` name in `RoomCard`.
Later I will maybe re-edit this mock data, it depends on use in `RoomDetailScreen`, but I want to separate these things and for using mock data, I will create another PR later.
=> [Tablet] Mock event data

frontend/tablet/src/screens/RoomDetailScreen/Header.tsx
Closes #81 
- Display current time and date in `RoomDetailScreen`,
- Time and date are updating every second.
=> [Tablet] Display current time and date

backend/app/api/calendar.py, backend/app/api/event.py, backend/app/api/room.py, backend/app/api/tenant.py, backend/app/services.py
Removed request arguments parameter deconstruction from all admin api methods and moved it to the services file
=> Moved parameter deconstruction api->services

backend/app/api/event.py, backend/app/api/room.py, backend/app/daos.py
Changes:
- Added option to request room list with-events or with-next-events-
- Added option to change duration of event. Usage: you specify number of minutes (integer negative or positive) and the length of the event will be updated accordingly-
- Added option to cancel event immediately.
Usage: `event/{id}/cancel `
- event that didn't start yet will be deleted
- event that already happened will not be affected
- only event that was currently running will be shortened to current time
=> Backend tablet api

backend/app/seedDB.py, backend/app/static/swagger.json
Changes: 
- Edited event seed script for database
- Updated swagger with all changes (changes from PR's #90,  #87 are also included)
=> Backend restructure

frontend/shared/models.ts, frontend/tablet/src/screens/RoomDetailScreen/Footer.tsx, frontend/tablet/src/screens/RoomDetailScreen/Footer/Footer.tsx, frontend/tablet/src/screens/RoomDetailScreen/Footer/NextEvent.tsx, frontend/tablet/src/screens/RoomDetailScreen/index.tsx, frontend/tablet/src/screens/RoomListScreen/index.tsx, frontend/tablet/src/utils.ts
- Room display next meeting and availability in `RoomDetailScreen`, based on mock data.
=> [Tablet] Next meeting and room availability

backend/app/api/building.py, backend/app/api/calendar.py, backend/app/api/city.py, backend/app/api/event.py, backend/app/api/room.py, backend/app/services.py, backend/app/utils.py
Changes:
- Added naming schemes conversion between json and dict to utils
- Added method to shared services that lets you create a response
- Used naming scheme conversion in converting request parameters and to create request method
- Replaced current solution of response creation in building, city, room, event and calendar apis
=> Json standardization

frontend/admin/src/components/Building/BuildingList.tsx, frontend/admin/src/components/Room/RoomEdit.tsx, frontend/admin/src/components/Room/RoomList.tsx, frontend/admin/src/components/Room/RoomShow.tsx
Updated fields to use reference for backend data.
=> [FE Admin] Updated fields to use reference

backend/app/user_dao.py
Hotfix for filters in `user_dao.py`
=> Hotfix for filters in get users

backend/app/user_dao.py
Hotfix for filters in `user_dao.py`
=> Hotfix for filters in user dao

backend/app/firebase_utils.py
=> Added uid to return value
